### ISSUE TITLE
After upgrade to Fedora 27, MPRIS extension integration broken

### ISSUE THREAD

**Issue by dkogias** [pithos/pithos#551] opened 2017-11-25 21:21 UTC
Upgraded from F26 to F27, pithos from rpmfusion now at 1.4.0-1.fc27

I also have the [Media Player Indicator](https://extensions.gnome.org/extension/55/media-player-indicator/) extension installed, via `extensions.gnome.org`.  I've updated to its latest version after the F27 system upgrade.

Pithos used to integrate with the extension, displaying, as default, on the system menu, under F26.  With F27 there is no integration.  Going to Preferences->Plugins I see that `Mpris` is turned off.  If I try to turn it on it turns off again, and the plugin slider is grayed out.  Hovering over it at that point shows "Failed to create DBus mpris service".

FWIW, Rhythmbox seems to still be integrating with the extension without issues.

**Comment by JasonLG1979** [comment] 2017-11-26 02:18
I am the owner of  [Media Player Indicator](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer) And also a contributor to Pithos. The extension and Pithos have been extensively tested against each other, and should work perfect. What is the output of the 1st few lines of ```pithos -d```? Specifically you're looking for a message about the session bus.

**Comment by JasonLG1979** [comment] 2017-11-26 02:23
Oh, never mind I know the problem. It was fixed in https://github.com/pithos/pithos/commit/c6dad7599aa84c43f47d58364468a59236702a88

@TingPing you want to merge at least that mediakeys PR and do that bug fix release? You're also the maintainer of the rpmfusion package too aren't you?

Anyway that's been fixed on master and a bug fix release is coming so I'm closing this.

**Closed by JasonLG1979** 2017-11-26 02:23 UTC

**Comment by JasonLG1979** [comment] 2017-11-26 02:25
Duplicate of https://github.com/pithos/pithos/issues/516

**Comment by dkogias** [comment] 2017-12-10 06:20
Just for posterity, this is fixed in Fedora with 1.4.1-1.fc27 - thanks @TingPing
