### ISSUE TITLE
Pithos 1.6.2 on Ubuntu 22.04.4 will not add new stations, only delete them.

### ISSUE THREAD

**Issue by Petesgalaxy** [pithos/pithos#708] opened 2024-03-18 17:08 UTC
I've been using 1.5.1 and it worked fine until it started randomly stopping. This was fixed in latest update, only now, I can't add new stations. I can delete them just fine.

**Comment by TingPing** [comment] 2024-03-20 15:42
Sounds like a duplicate of #706

**Closed by TingPing** 2024-03-20 15:42 UTC
