### ISSUE TITLE
Invalid username and/or password

### ISSUE THREAD

**Issue by jam01** [pithos/pithos#654] opened 2021-06-15 16:27 UTC
~After a recent update to my Fedora install~ 

Pithos stopped working with the following message:
```ERROR - pandora:json_call:233 - fault code: 1001 INVALID_AUTH_TOKEN message: Invalid username and/or password```

I'm sure the creds are correct because I can correctly login from the website. And they haven't changed between when pithos worked and now.

Pithos 1.4.1
Fedora 33 - pithos.noarch 1.4.1-9.fc32

**Comment by jacksontj** [comment] 2021-06-15 16:34
I just ran into this same issue this morning. On my system I made no OS changes, I was using it successfully on Pithos 1.5.0 yesterday and this morning it isn't working with the same "Invalid username and/or password" message. I confirmed that I can log in through the pandora website (works fine) and I attempted upgrading to Pithos 1.5.1 (same error). So this sounds like something done on the Pandora side :/

**Comment by theherodied** [comment] 2021-06-15 16:47
Same issue here with Pithos 1.5.1 and Pithos 1.1.2. Was working fine then stopped.

**Comment by dobsonj** [comment] 2021-06-15 16:52
Same issue for me on Fedora 34 as of today, pithos-1.5.1-1.fc34

**Comment by dmartin-isp** [comment] 2021-06-15 18:12
Me too.  Change on Pandora's end?

**Comment by bkw777** [comment] 2021-06-15 18:13
Same issue with both pianobar and pandoroid. all 3 stopped working just now at the same time, while the web page works, so, Pandora changed something on their end.

**Comment by kpgrelling** [comment] 2021-06-15 20:49
Same here.  Flatpak version 1.5.1 on Ubuntu 20.04.  

The "Getting Started" page at [https://developer.pandora.com](https://developer.pandora.com) now says only "We're not accepting new access requests at this time. Please check again later."  Seems a little onerous.

**Comment by scareduck** [comment] 2021-06-15 21:27
Same. Pandora 1.5.1 on Fedora 34.

**Comment by RanTheLab** [comment] 2021-06-15 22:17
Pithos 1.5.1 on Ubuntu 20.04 and FREE Pandora account is working.

**Comment by majorhayes** [comment] 2021-06-15 22:22
Pithos 1.5.1 on Ubuntu 20.10. Tried with a paid and a free account. Login fails on both.

**Comment by clarkevans** [comment] 2021-06-16 14:10
Pithos 1.5.1. on Ubuntu 20.04 -- failed with Pandora Plus account (worked yesterday).

**Comment by draik** [comment] 2021-06-16 14:39
Replicated on Pithos 1.5.1 (source), but happening on Pithos 1.1.2 from Ubuntu repo as well:

ERROR - pandora:json_call:142 - fault code: 1001 message: Invalid username and/or password

Pithos 1.1.2 can be fixed by unchecking the "Pandora One Subscriber" option. However, this isn't present in Pithos 1.5.1 (source), and continues with the same error.

**Comment by rwdougla** [comment] 2021-06-16 15:25
There is a thread going on with the Pandora community site about this: https://community.pandora.com/t5/Desktop/Can-t-log-in-on-pithos/td-p/68153

**Comment by jellisii** [comment] 2021-06-16 15:38
@clarkevans Spotify seems to have Linux support first party:  https://www.spotify.com/us/download/linux/

**Comment by clarkevans** [comment] 2021-06-16 16:14
Perhaps it's time to have some sort of open music cooperative and more directly support artists.

**Comment by kpgrelling** [comment] 2021-06-16 17:51
It just started working for me again.  I turned in a support request to Pandora and got an inane "This is an unauthorized app" response from a level one tech.  I asked that it be forwarded to a developer, and now it seems to be working again.

Can someone else verify its working again?

**Comment by jellisii** [comment] 2021-06-16 17:53
I can verify that it's working again with the latest master.

**Comment by theherodied** [comment] 2021-06-16 17:59
Can confirm Pithos 1.5.1 Flatpak and Ubuntu 1.1.2 deb are working.

**Comment by dmw78** [comment] 2021-06-16 18:56
Pithos 1.5.1 starting working again for me after a reboot.

**Comment by bkw777** [comment] 2021-06-16 19:02
Working again.

**Closed** 2021-06-16 20:07 UTC

**Comment by jonathonf** [comment] 2021-10-08 23:33
Same thing seems to be occurring again... though now I can't log in to the website and even resetting the password fails...

**Comment by theherodied** [comment] 2021-10-09 01:12
> Same thing seems to be occurring again... ~though now I can't log in to the website and even resetting the password fails...~

It appears to just be a service outage. 

https://downdetector.com/status/pandora/

**Comment by jonathonf** [comment] 2021-10-12 00:04
Unfortunately it persists. Web login works, Pithos login does not.

**Comment by jonathonf** [comment] 2021-10-19 00:03
> There are literally countless ways for that to happen.

AKA "I don't know".

All of what you say may be valid in a general sense, but the fact is that it's not down to the difference between web client and Pithos. It has been established by other people that Pithos itself works, therefore Pithos - as a client - is not being blocked or firewalled by Pandora.

If you're saying that Pandora employs some sort of TCP/IP traffic inspection that classifies certain traffic from certain IP ranges differently then I'm not sure how capturing local network traffic is going to help identify that.

On the other hand, if the difference is that Pithos works for people with a Premium account but not for Free or Plus accounts, then that would be a cognitively straightforward reason - frustrating, disappointing, but at least understandable.

**Comment by nhumrich** [comment] 2021-12-09 17:52
Did this break again? Pithos no longer working for me, same error "INVALID_AUTH_TOKEN".

**Comment by bkw777** [comment] 2021-12-09 17:56
Working for me just now. paid account.

**Comment by theherodied** [comment] 2021-12-09 17:58
> Did this break again? Pithos no longer working for me, same error "INVALID_AUTH_TOKEN".

Working for me as well. Pandora Plus account.

**Comment by nhumrich** [comment] 2021-12-09 18:27
ok thanks. not sure what is wrong then. Will look deeper.

**Comment by BigCityCat** [comment] 2022-10-30 14:52
I just wanted to say that this happens to me when on VPN. Works fine on an unencrypted connection.

**Comment by scareduck** [comment] 2022-10-30 16:30
The problem eventually resolved itself. I was never using a VPN.

-- 
Sent from Rob McMillin’s iPad
Dramatis personae: ONB Libby, NESR Jed, and various NESR fosters
Location: Woofwood, Little Rock, AR
