### ISSUE TITLE
SSL Certificate Verify Failed (LibreSSL)

### ISSUE THREAD

**Issue by beanpole135** [pithos/pithos#278] opened 2016-03-17 13:31 UTC
**System:**
* Pithos 1.0.0, 
* FreeBSD 11-CURRENT 
* LibreSSL 2.3.2

**Problem:**
Pithos consistently fails to connect to the pandora servers with an SSL certificate verification error.
`ERROR - pandora:json_call:115 - Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>`

**Possible Solution:**
I believe the main difference in the LibreSSL vs OpenSSL implementations (for an end-user/app) is that LibreSSL only supports TLS encryption protocols whereas OpenSSL supports both SSL & TLS encryption protocols. Since the SSL2/3 protocols are widely considered inferior/insecure compared to the TLS protocols, this might be easily fixed by specifying that your network socket method use TLS encryption whenever possible.

**Comment by beanpole135** [comment] 2016-03-17 13:35
FYI: I just realized that the FreeBSD version of Pithos is a few versions behind. I will respond back after getting the port maintainer to update the port and I re-test it.

**Comment by beanpole135** [comment] 2016-03-17 14:18
Ok, I just rebuit/tested the newest version of pithos (1.1.2) and the problem still persists: reopening the issue...

Additional Information (running `pithos -v`)
```
/usr/local/lib/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/local/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/local/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
INFO - pithos:do_activate:1118 - Pithos 1.1.2
INFO - plugin:enable:38 - Enabling module mediakeys
ERROR - mediakeys:on_enable:138 - Could not bind media keys
INFO - plugin:enable:38 - Enabling module notification_icon
INFO - plugin:enable:38 - Enabling module mpris
ERROR - pandora:json_call:129 - Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
```

**Comment by TingPing** [comment] 2016-03-17 14:22
This was fixed in [1.1.2](https://github.com/pithos/pithos/releases/tag/1.1.2)

**Comment by TingPing** [comment] 2016-03-17 14:23
Oh sorry I missed your new comment.

**Comment by TingPing** [comment] 2016-03-17 14:43
So the problem is not SSL, their web server actually is TLS only. You can check out their cert yourself to see what libressl might have removed support for: https://www.ssllabs.com/ssltest/analyze.html?d=internal-tuner.pandora.com

Eitherway if the problem is on libressl not supporting something there is nothing we can do about it.

**Comment by beanpole135** [comment] 2016-03-17 16:48
Sounds good - I will poke the guy who manages the LibreSSL port here and see if this is something he broke (or can fix) then....

In the meantime, would it be possible for you to put in a button to accept an SSL cert anyway if this type of error is reported (with appropriate warnings)? That would at least allow pithos to be usable while waiting on upstream changes.

**Comment by TingPing** [comment] 2016-03-17 17:32
> In the meantime, would it be possible for you to put in a button to accept an SSL cert anyway if this type of error is reported (with appropriate warnings)?

I'm rather unlikely to do so since we don't even know what the full problem is yet and its limited to a small group of users.

**Closed** 2016-03-17 19:17 UTC

**Comment by beanpole135** [comment] 2016-03-21 13:23
Just to follow up with this:
I discovered that the version of LibreSSL I was using was the current development version (2.3.2), switching to the current release version (2.2.6) fixed the problem completely. I am following up with the LibreSSL developer/porter on FreeBSD to make sure that this issue with LibreSSL gets fixed in the devel version before the next release.
