### ISSUE TITLE
Pithos doesn't send favorite song status to last.fm

### ISSUE THREAD

**Issue by dttvinh** [pithos/pithos#152] opened 2015-02-16 05:20 UTC
There's a small bug in the send_rating method (in scrobble.py) that prevents pithos from update love/ban status on last.fm. Below is what I did to make it works (don't know if there's any other bugs around or not though).

```py
def send_rating(self, window, song):
    if song.rating: 
        track = self.network.get_track(song.artist, song.title)
        if song.rating == 'love':
            self.worker.send(track.love)
        elif song.rating == 'ban':
            self.worker.send(track.ban)
        else: # Should equal None here
            self.worker.send(track.unlove)
        logging.info("Sending song rating to last.fm")
```
and finally, register it  in the on_enable method:

```py
self.song_rating_changed_handle = self.window.connect('song-rating-changed', self.send_rating)
````

**Comment by glennimoss** [comment] 2015-03-27 20:36
See this bug from days gone by: https://bugs.launchpad.net/pithos/+bug/636600

Apparently there isn't a 1:1 semantic match between Pithos/Pandora and Last.fm love/ban/whatever model.

Thus I'm closing this as "Works as intended."

**Closed by glennimoss** 2015-03-27 20:36 UTC
