### ISSUE TITLE
In the gnome media player extension the album cover does not change only with pithos. 

### ISSUE THREAD

**Issue by person666** [pithos/pithos#263] opened 2016-01-14 11:53 UTC
The glitch only occurs if the gnome media extension is open. If I skip to the next track using my keyboard or the buttons in the extension while the extension is open the album cover does not change(this does not occur with every other media app I have used with it so it is a pithos glitch). It may also occur any time the extension has been viewed even when the song change occurs when the extension is hidden(I have not done enough testing to determine that this is accurate. 

When the glitch is occurring if I click the album cover to enlarge it in the extension the correct cover flashes. After a unknown number of songs unskipped with the extension not visible the cover sometimes gets correct but it then does not keep up with changing the cover when the next song comes on.

**Comment by FriedMicro** [comment] 2016-01-17 00:29
I am also having this issue. With a previous version of the extension I did not however therefore I doubt the issue is Pithos.

**Comment by person666** [comment] 2016-01-17 03:23
I have tested the newest version of the extension with several other apps
the problem is pithos. I have also had problems with the cairo dock music
widget.

**Comment by FriedMicro** [comment] 2016-01-17 05:42
Not exactly flawless logic on either hence the word "doubt". It's possibly a regression in the extension due to the way pithos is implented with MPRIS2 (this is a long-running problem). It states the application has been tested on the github page for the extension and the Pithos code has not changed since that point. I can personally vouch it was working before an extension update. Either way such point is philosophy. 

Either A the implementation is redone in Pithos to match what the extension expects or B the regression in the extension is found.

The proper solution is the later since it is not a good decision to tie Pithos into the extension and fixing the extension will result in other applications having their issues resolved as well.

On January 16, 2016 10:24:00 PM EST, person666 <notifications@github.com> wrote:
>I have tested the newest version of the extension with several other
>apps
>the problem is pithos. I have also had problems with the cairo dock
>music
>widget.
>
>On Sat, Jan 16, 2016, 7:29 PM FriedMicro <notifications@github.com>
>wrote:
>
>> I am also having this issue. With a previous version of the extension
>I
>> did not however therefore I doubt the issue is Pithos.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pithos/pithos/issues/263#issuecomment-172279253>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pithos/pithos/issues/263#issuecomment-172286799

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by FriedMicro** [comment] 2016-01-17 06:10
Issue is present in release and master branch.

**Comment by FriedMicro** [comment] 2016-01-17 06:24
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/212

**Comment by JasonLG1979** [comment] 2016-02-27 01:22
@person666 give this a test and see if that does the trick.
https://github.com/JasonLG1979/pithos/tree/MPRIS_fixes

**Comment by JasonLG1979** [comment] 2016-04-02 21:28
@TingPing this should also be fixed with the MPRIS fixes.

**Comment by TingPing** [comment] 2016-04-02 21:29
Fixed by 32946f26ad2bcb448455c6b2cf6789628d4cf182

**Closed by TingPing** 2016-04-02 21:29 UTC

**Comment by person666** [comment] 2016-04-02 22:44
Thanks. It works great now!
