### ISSUE TITLE
Feature request: crossfade plugin

### ISSUE THREAD

**Issue by pixelherodev** [pithos/pithos#524] opened 2017-10-15 03:00 UTC
Request: a plugin that loads the next song before the currently playing one is done and crossfades. The ability to specify time would also be nice.

This just occurred to me, but beginning to load the next song before the playing one is done can also help prevent a delay on slower internet connections.

**Comment by JasonLG1979** [comment] 2017-10-15 06:51
Crossfading from what I can tell is a bit of a hack with Gstreamer(our audio backend) as I don't think there is an actual dedicated crossfade Gstreamer element. Most players I've seen achieve crossfading by actually having 2 audio pipelines and leapfrogging them. That's all good and well for local files because there's no buffering involved. But for our use case crossfading just doesn't work very well or at all. I've played with the idea in the past and the results were less than ideal.

Having 2 audio pipelines ofc adds to resource usage and makes the player logic crazy more complicated. The big thing is buffering though. There's no way to know exactly how long it's going to take to buffer the next song. So even if you set say a 2 sec crossfade that crossfade may not happen if buffering takes longer that anticipated.

It's just not worth the added code complexity and effectively doubling the player's resource usage for something that doesn't work very well.

**Comment by pixelherodev** [comment] 2017-10-22 18:34
There seems to be an example of how to do it in the `bad` plugin set.
https://github.com/GStreamer/gst-plugins-bad/blob/master/tests/examples/compositor/crossfade.c

**Comment by JasonLG1979** [comment] 2017-10-22 18:38
That's a video crossfader.

**Comment by JasonLG1979** [comment] 2017-10-22 19:00
Like I said, the problem is not that crossfading in Gstreamer is impossible or that I need an example. The problem is that our audio is network streams. That causes the problem of that we don't know how long it's going to take to buffer up the crossfaded part of the next song. (see my previous comment) A solution to that could be to start caching the next song very early but then you could end up caching songs you may never actually play. The user could skip, tired or ban the song after it's cached and then you've just wasted time and bandwidth.

Like I said it's not worth the trouble.

 

> This just occurred to me, but beginning to load the next song before the playing one is done can also help prevent a delay on slower internet connections.

Nope. It will make things worse because now you're trying to stream 2 songs at once.

**Comment by JasonLG1979** [comment] 2017-11-04 15:01
@pixelherodev I'm going to close this as I don't think it's currently practical or beneficial. If in the future Gstreamer creates a more "out of the box" audio crossfading solution it may be revisited.

**Closed by JasonLG1979** 2017-11-04 15:01 UTC
Labels: enhancement
