### ISSUE TITLE
MPRIS metadata is missing the mpris:length field

### ISSUE THREAD

**Issue by maddin77** [pithos/pithos#261] opened 2015-12-21 23:18 UTC
Hi,

it seems like the `mpris:length` metadata field is missing, which means i'm not able to find out the total duration of the current song.

Is there another way to get the duration? Or if not, is that something that could be added in the future?

**Comment by TingPing** [comment] 2015-12-21 23:30
I think @JasonLG1979 brought this up in a previous issue. Would be a good addition.

**Comment by JasonLG1979** [comment] 2016-02-14 05:31
The problem is that MPRIS expects the track length when the rest of the meta data is loaded but we don't know it yet at that point. A work around would be to use the duration provided by Pandora but it's not very accurate.

**Comment by JasonLG1979** [comment] 2016-02-27 01:18
After testing it on various applets, even if I get the length from Pandora so it is known at song change just like the rest of the metadata, It's pretty dang flaky.
 
Ubuntu's sound menu of course doesn't support it, so that's that.

 The Media player indicator GNOME extension will show it if you toggle the setting on then off again.

The default Cinnamon sound applet doesn't show it and has no such toggle.

The only applet I can get to work correctly is:

https://github.com/Koutch/Cinnamon-sound-with-apps-volume

I started an issue with Media player indicator to try to find out if it's a bug on our side or theirs.

https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/246

**Comment by JasonLG1979** [comment] 2016-02-27 16:30
@maddin77 give this branch a try. IMHO it vastly improves MPRIS support Pithos, including providing mpris:length.

**Comment by maddin77** [comment] 2016-02-27 19:52
Yes, that seems to work as expected. Thanks.

I also tried the GNOME mediaplayer extension ([r545-1 from the AUR](https://aur.archlinux.org/packages/gnome-shell-extension-mediaplayer-git/)), and i can't seem to reproduce the issue described in eonpatapon/gnome-shell-extensions-mediaplayer#246. The position slider shows up and seems to display the correct value for me.

**Comment by JasonLG1979** [comment] 2016-02-27 20:06
> I also tried the GNOME mediaplayer extension (r545-1 from the AUR), and i can't seem to reproduce the issue described in eonpatapon/gnome-shell-extensions-mediaplayer#246. The position slider shows up and seems to display the correct value for me.

With which branch?

**Comment by JasonLG1979** [comment] 2016-02-27 20:21
@TingPing you could maybe merge this issue with #268 maybe?

**Comment by maddin77** [comment] 2016-02-27 21:18
> With which branch?

Pithos: https://github.com/JasonLG1979/pithos/tree/MPRIS_fixes
gnome-shell-extensions-mediaplayer: https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/tree/master

GNOME Shell 3.18.3 in case that helps.

**Comment by JasonLG1979** [comment] 2016-02-27 22:18
That branch takes into account the extensions quirks. It works for me on Ubuntu 15.10 and a hacked up GNOME 3.16 too.

**Comment by JasonLG1979** [comment] 2016-02-27 22:29
Oh and I was using the extensions master branch as well.

**Comment by JasonLG1979** [comment] 2016-02-27 23:08
Winner winner chicken dinner it works dang good in Fedora 23 also with GNOME 3.18.2 and the extension from the GNOME extension site.

**Comment by JasonLG1979** [comment] 2016-02-29 20:18
@maddin77 I've amended my commit to include fixes for applets(including gnome-shell-extensions-mediaplayer) reusing the previous song's cover is no cover is given to us by Pandora. Care to test it out?

**Comment by maddin77** [comment] 2016-03-01 10:36
> I've amended my commit to include fixes for applets(including gnome-shell-extensions-mediaplayer) reusing the previous song's cover is no cover is given to us by Pandora. Care to test it out?

Works fine on my end.

**Comment by maddin77** [comment] 2016-03-04 20:21
I just noticed that sometimes when skipping a song, the title/artist/cover/duration metadata in [gnome-shell-extensions-mediaplayer](https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer) doesn't get updated. It still shows the data of the previous song. Current position/volume is fine.

Here's the log (started with `--debug` & `--verbose`)

```
INFO - pithos:start_song:561 - Starting song: index = 4
INFO - pandora:audioUrl:413 - Using audio quality highQuality: 64 aacplus
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pithos/plugins/_mpris.py", line 75, in _metadatachange_handler
    {'Metadata': dbus.Dictionary(self._update_metadata(song),
  File "/usr/lib/python3.5/site-packages/pithos/plugins/_mpris.py", line 110, in _update_metadata
    '/org/mpris/MediaPlayer2/TrackList/%s' %song.trackToken),
ValueError: Invalid object path '/org/mpris/MediaPlayer2/TrackList/Pz7aVTfn9aO4C45BuMLBy7Dye0-VqnnOVRcKPdMkOl3qlFPBEdhBqf6k61DbWBvn7': contains invalid character '-'
DEBUG - pithos:handler:818 - Found tag "audio-codec" in stream: "MPEG-4 AAC audio" (type: <class 'str'>)
DEBUG - pithos:handler:818 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:818 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:818 - Found tag "datetime" in stream: "2008-01-24T11:05:56Z" (type: <class 'str'>)
DEBUG - pithos:handler:818 - Found tag "container-format" in stream: "ISO MP4/M4A" (type: <class 'str'>)
DEBUG - pithos:on_gst_async_done:752 - on_gst_async_done
INFO - pithos:check_if_song_is_ad:834 - Not an Ad..
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pithos/plugins/_mpris.py", line 75, in _metadatachange_handler
    {'Metadata': dbus.Dictionary(self._update_metadata(song),
  File "/usr/lib/python3.5/site-packages/pithos/plugins/_mpris.py", line 110, in _update_metadata
    '/org/mpris/MediaPlayer2/TrackList/%s' %song.trackToken),
ValueError: Invalid object path '/org/mpris/MediaPlayer2/TrackList/Pz7aVTfn9aO4C45BuMLBy7Dye0-VqnnOVRcKPdMkOl3qlFPBEdhBqf6k61DbWBvn7': contains invalid character '-'
DEBUG - pithos:on_gst_buffering:853 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (24%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (25%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (42%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (51%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (25%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (43%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (52%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (61%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (76%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (100%)
DEBUG - pithos:on_gst_buffering:864 - Buffer 100%. Song starting
```
Another one, in case that helps:
```
INFO - pithos:start_song:561 - Starting song: index = 22
INFO - pandora:audioUrl:413 - Using audio quality highQuality: 64 aacplus
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pithos/plugins/_mpris.py", line 75, in _metadatachange_handler
    {'Metadata': dbus.Dictionary(self._update_metadata(song),
  File "/usr/lib/python3.5/site-packages/pithos/plugins/_mpris.py", line 110, in _update_metadata
    '/org/mpris/MediaPlayer2/TrackList/%s' %song.trackToken),
ValueError: Invalid object path '/org/mpris/MediaPlayer2/TrackList/PsB6h-iFuTJEC45BuMLBy7GKAHValqXvzRcKPdMkOl3qlFPBEdhBqf6o4NLt5JEZn': contains invalid character '-'
DEBUG - pithos:on_gst_buffering:853 - Buffering (1%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (1%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (1%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (2%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (3%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (4%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (3%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (42%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (33%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (25%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (16%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (7%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (0%)
DEBUG - pithos:handler:818 - Found tag "audio-codec" in stream: "MPEG-4 AAC audio" (type: <class 'str'>)
DEBUG - pithos:handler:818 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:818 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:818 - Found tag "datetime" in stream: "2008-01-22T10:48:36Z" (type: <class 'str'>)
DEBUG - pithos:handler:818 - Found tag "container-format" in stream: "ISO MP4/M4A" (type: <class 'str'>)
DEBUG - pithos:on_gst_async_done:752 - on_gst_async_done
INFO - pithos:check_if_song_is_ad:834 - Not an Ad..
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pithos/plugins/_mpris.py", line 75, in _metadatachange_handler
    {'Metadata': dbus.Dictionary(self._update_metadata(song),
  File "/usr/lib/python3.5/site-packages/pithos/plugins/_mpris.py", line 110, in _update_metadata
    '/org/mpris/MediaPlayer2/TrackList/%s' %song.trackToken),
ValueError: Invalid object path '/org/mpris/MediaPlayer2/TrackList/PsB6h-iFuTJEC45BuMLBy7GKAHValqXvzRcKPdMkOl3qlFPBEdhBqf6o4NLt5JEZn': contains invalid character '-'
DEBUG - pithos:on_gst_buffering:853 - Buffering (18%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (43%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (60%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (69%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (76%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (85%)
DEBUG - pithos:on_gst_buffering:853 - Buffering (100%)
DEBUG - pithos:on_gst_buffering:864 - Buffer 100%. Song starting
```

**Comment by JasonLG1979** [comment] 2016-03-04 20:30
I noticed that to. I was using the trackToken provided by Pandora for the trackid.'-' is an invalid character for a Dbus/MPRIS object path. I amended my commit and now it uses the song index plus a 56 digit string of random numbers. It had the added benefit of that we can get the song.index back out of the trackid.

```
    def _unique_trackid_generator(self, window, song):
        """The trackid must be a unique and valid object path for each song, although the path does not
        have to actually point to anything. We use the song.index as our starting point for our trackid
        so that later when clients refer to songs by their trackid we can extract the song.index for use
        in Pithos for things like skipping to, or rating a specific in a tracklist.

        https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-marshaling-object-path
        https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Metadata
        https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html#Mapping:Metadata_Map
        """

        random_numbers = ''.join(str(random.randint(0, 9)) for x in range(56))
        self._unique_trackid = ('/org/mpris/MediaPlayer2/TrackList/%s%s' %(song.index, random_numbers))

    def _song_index_from_trackid(self, trackid):
        """Extracts the song.index from a trackid by slicing the object path
        from the begining and the random numbers from end.
        """ 
        return int(trackid[34:-56])

    def _update_metadata(self, song):
        """metadata changed - sets the info for the current song.

        This method is not typically overriden. It should be called
        by implementations of this class when the player has changed
        songs.
            
        named arguments:
            artists - a list of strings representing the artists"
            album - a string for the name of the album
            title - a string for the title of the song

        """
        #map pithos ratings to something MPRIS understands
        if song.rating == 'love':
            userRating = 5
        else:
            userRating = 0

        #try to use the generic audio MIME type icon from the user's current theme
        #for the cover image if we don't get one from Pandora else return an empty string
        #Workaround for: 
        #https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/248

        if song.artUrl is not None:
            artUrl = song.artUrl
        else:
            icon_theme = Gtk.IconTheme.get_default()
            icon_info = icon_theme.lookup_icon('audio-x-generic', 48, 0)
            if icon_info is not None:
                artUrl = "file://%s" %icon_info.get_filename()
            else:
                artUrl = ""

        self._metadata = {"mpris:trackid": self._unique_trackid,
                          "xesam:title": song.title or "Title Unknown",
                          "xesam:artist": [song.artist] or ["Artist Unknown"],
                          "xesam:album": song.album or "Album Unknown",
                          "xesam:userRating": userRating,
                          "mpris:artUrl": artUrl,
                          "xesam:url": song.audioUrl,
                          "mpris:length": dbus.Int64(self._current_duration),
                          "pithos:rating": song.rating or "",}

        return self._metadata
```

**Comment by JasonLG1979** [comment] 2016-03-04 20:47
Give it a try now. Since the amend I haven't seen any problems.

**Comment by maddin77** [comment] 2016-03-04 21:53
Thanks, no problems now. :+1:

**Comment by JasonLG1979** [comment] 2016-03-04 21:54
> Thanks, no problems now.

Thank you for testing it!!!

**Comment by JasonLG1979** [comment] 2016-03-12 12:08
@maddin77, I amended my commit(again...) to get rid of a workaround to an upstream bug that has since been fixed, could you give it a test again? Hopefully after a couple more upstream bugs that I'm still working around are cleared @TingPing will merge it(?) In the commit I also added support for clients setting song ratings. If/when my PR is merged I plan on seeing if I can work with some clients to add support for reading and setting Pithos style rating(Love, Tired, Ban)

**Comment by maddin77** [comment] 2016-03-13 11:45
No problems here. The song rating seems to work fine in gnome-shell-extensions-mediaplayer as well.

**Comment by JasonLG1979** [comment] 2016-03-13 18:03
> The song rating seems to work fine in gnome-shell-extensions-mediaplayer as well.

I basically just mapped a "Loved" rating to 5 and everything else to 0 in "xesam:userRating" in the metadata. "xesam:userRating" is in the MPRIS spec. We also expose a custom "pithos:rating" value that holds the actual ratings as a string("love", "ban", "tired", and "" for not rated) Setting ratings is not a part of the spec neither is custom ratings, so it would be up to the clients if they want to enable the reading of custom ratings and the setting of ratings. It would require Pithos specific code on their part.

**Comment by JasonLG1979** [comment] 2016-03-13 18:17
I think I might amend my PR 1 more time to add logging to the MPRIS plugin so I can get the trackId's.

**Comment by JasonLG1979** [comment] 2016-03-13 18:41
There done. Now _mpris.py logs the trackid's. You can see the trackid by running Pithos from the command line with ```pithos -v```.

Look for lines that  begin with ```INFO - _mpris:_unique_trackid_generator:102```. It will give you the MPRIS trackid for a particular song.index.

You can then test the rating method from the command line with:
```
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.pithos /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.RateSong objpath:[trackid] 9495543818 string:[rating]
```

For example:
```
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.pithos /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.RateSong objpath:/org/mpris/MediaPlayer2/TrackList/178725440256034456436288345160729471482803510169495543818 string:'love'
```

**Comment by JasonLG1979** [comment] 2016-04-02 17:28
@TingPing https://github.com/pithos/pithos/commit/32946f26ad2bcb448455c6b2cf6789628d4cf182 fixes this.

**Closed** 2016-04-02 17:37 UTC
Labels: enhancement, plugin
