### ISSUE TITLE
Sound output delay when streaming via Chromecast

### ISSUE THREAD

**Issue by xmbwd** [pithos/pithos#417] opened 2017-02-10 16:33 UTC
Pithos has no buffering/delay issues for me when using speakers or bluetooth.  But when using Chromecast, the delay starts at around 3-5 seconds, then builds over time.  If I listen for a few hours, it will expand to around 45 seconds.  

I initially thought it was `pulseaudio-dlna`, which is providing the connection to the Chromecast.  But the behavior seems to be limited to Pithos (e.g., it does not occur when using `pulseaudio-dlna` and: a web player for Pandora, Tomahawk, or Spotify (client)).  Here is [the link](https://github.com/masmu/pulseaudio-dlna/issues/260#issuecomment-270902579) to the issue I raised in `pulseaudio-dlna`.

Maybe it is a combination of the two.  Any ideas?

**Comment by JasonLG1979** [comment] 2017-02-10 16:52
That's not anything we have control of. We just basically hand off the song url to Gstreamer we don't handle audio latency in any way.

**Comment by JasonLG1979** [comment] 2017-02-10 17:02
I wonder how hard it would be for us to write our own dlna plugin? Skip the middle man.

**Comment by xmbwd** [comment] 2017-02-10 17:05
Adding a DLNA plugin would be awesome!  

So Gstreamer is the culprit.  Is it possible these other players are bypassing it in some way?  Or feeding it different settings?

**Comment by JasonLG1979** [comment] 2017-02-10 17:16
> Adding a DLNA plugin would be awesome!

I'm looking into it. I'm not sure how the DLNA protocol works. There are a couple DLNA python modules floating around I'll see if I can figure it out.



> So Gstreamer is the culprit. Is it possible these other players are bypassing it in some way? Or feeding it different settings?

I'm not sure there's so much at play it's hard to say where the problem is? I'm not exactly sure how pulseaudio-dlna works. It looks like it just pushes whatever pulseaudio is outputting as one continuous stream right? If you listen for hours there's going to be latency drift on a continuous stream there's not much you can do about that especially when you're talking about consumer audio gear like a Chromecast.

**Comment by xmbwd** [comment] 2017-02-10 17:32
True.  The part I don't get is why the latency drift of pulseaudio-dlna differs by player.  It is also worth noting that Google Chrome's built in casting capability (i.e., not using pulseaudio-dlna) has no latency or drift.

**Comment by JasonLG1979** [comment] 2017-02-10 19:24
> True. The part I don't get is why the latency drift of pulseaudio-dlna differs by player.

Did you listen to other players for hours like you did Pithos?

**Comment by xmbwd** [comment] 2017-02-10 19:28
Unfortunately, yes.  I've had to move to other players b/c I need the ability to stop the sound fairly immediately.

**Comment by JasonLG1979** [comment] 2017-02-10 19:31
I also don't know what the native bit depth of pulseaudio-dlna or the Chromecast is? Or if pulseaudio-dlna compresses the stream. Any resampling is going to add latency. for the least amount of latency you're going to want to find a bit depth and sampling rate that they all have in common. MP3 and MP4 audio doesn't technically have a bit depth but the sampling rate is 44100 for what Pandora gives us.

**Comment by JasonLG1979** [comment] 2017-02-10 19:33
I believe that Gstreamer uses a bit depth of 32float when converting?

**Comment by JasonLG1979** [comment] 2017-02-10 20:38
Looking in the Tomahawk source it seems to be using VLC for it's audio backend. I have no idea of the audio backend of Spotify? Can you test with other players Gstreamer audio backends like Exaile, Lollypop, Rhythmbox or GNOME Music to confirm it's a Gstreamer issue? In particular test network audio streams like internet radio.

**Comment by xmbwd** [comment] 2017-02-10 20:56
Happy to.  What kind of output do you need (and how do I obtain it)?

**Comment by JasonLG1979** [comment] 2017-02-10 21:03
Exaile, Lollypop and Rhythmbox all have the ability to play internet radio. If you would fire up one of those players and play an internet radio station for a while and see what happens.

**Comment by xmbwd** [comment] 2017-02-10 21:18
Testing Rhythmbox using Jamendo.  The initial delay is ~2 secs.

**Comment by JasonLG1979** [comment] 2017-02-10 21:48
Sounds like a Gstreamer issue then?

**Comment by JasonLG1979** [comment] 2017-02-10 21:51
Oh a quick question. Does the Chromecast show anything from PulseAudio that identifies the stream? Basically do you know if it reads the PulseProps?

**Comment by JasonLG1979** [comment] 2017-02-10 22:07
> It expanded pretty quickly to 10 seconds....
It would be nice if it had a passthough audio mode. Seems like a waste of time for gstreamer/pulseaudio to convert it from a  mp3 to PCM and then convert it back to mp3...

**Comment by xmbwd** [comment] 2017-02-10 22:07
Chromecast (via Google's Home app) shows the name of the player being used (e.g., Tomahawk or Pithos), then:
```
Liveaudio on ubuntu
Default Media Receiver
```

**Comment by JasonLG1979** [comment] 2017-02-10 22:11
> Chromecast (via Google's Home app) shows the name of the player being used (e.g., Tomahawk or Pithos), then:
> 
> Liveaudio on ubuntu
> Default Media Receiver

So no then it doesn't. It's a shame they can read the PulseProps and if the player provides them they could show the players name and the title and album of the audio.

**Comment by JasonLG1979** [comment] 2017-02-10 22:15
Correction: It looks like they try to get some info from the props. Maybe the Chromecast just doesn't display it.

**Comment by JasonLG1979** [comment] 2017-02-11 00:18
@xmbwd see https://github.com/masmu/pulseaudio-dlna/issues/260#issuecomment-279086850

My thought is that they can skip Gstreamer and PulseAudio all tougher if we provide the actual audio url in the pulse props. They could stream that directly and skip a lot a overhead.

**Comment by JasonLG1979** [comment] 2017-02-11 00:19
@TingPing any objections to adding more PulseProps, or any thoughts on the subject in general?

**Comment by TingPing** [comment] 2017-02-11 00:23
Sounds fine.

**Comment by JasonLG1979** [comment] 2017-02-11 00:25
OK I'll put in a quick PR for you to hopefully merge ;P

**Comment by TingPing** [comment] 2017-02-11 00:50
@JasonLG1979 Perhaps a silly question, but how does setting a filename help staying in sync when it conveys no information of play/pause state?

**Comment by JasonLG1979** [comment] 2017-02-11 00:55
That's up to the them. AFAIK there's a way for the client to tell the server to pause/play and what not. How they do that is not really my concern. I'm just giving them a little more info what they do with it is on them.

**Comment by JasonLG1979** [comment] 2017-02-11 00:56
They could for example hook to our MPRIS interface? That wouldn't be hard.

**Comment by JasonLG1979** [comment] 2017-02-11 00:57
For that matter they could hook to the MPRIS interface for everything. They'd get all the controls/info they'd ever need.

**Comment by TingPing** [comment] 2017-02-11 00:58
Yea but that sounds like a new project basically, mpris-dlna :P

**Comment by JasonLG1979** [comment] 2017-02-11 00:58
A MPRIS-DLNA bridge would be brilliant!!!

**Comment by JasonLG1979** [comment] 2017-02-11 01:16
I may actually look into creating a MPRIS-DLNA bridge. I'm pretty competent as far as MPRIS is concerned. I'll take a look at their DLNA bits and see what I can come up with?

**Comment by JasonLG1979** [comment] 2017-02-12 07:46
@xmbwd I'm going to close this as it's clearly either a bug in pulsesudio-dlna or Gstreamer. If you get any info otherwise feel free to reopen it.

**Closed by JasonLG1979** 2017-02-12 07:46 UTC
