### ISSUE TITLE
Strange playback issue.

### ISSUE THREAD

**Issue by MC42** [pithos/pithos#228] opened 2015-09-10 00:27 UTC
Okay, first of all, my version is 1.1.1 from the PPA on the website, running in Ubuntu 15.04.  Whenever I play a song, it plays fine, but upon completion, it stops, says buffering, and doesn't play.  I press play, and it resumes playback, but it gets annoying.

When I use the -vv option, this fills the console.  
![selection_004](https://cloud.githubusercontent.com/assets/6531081/9777316/b811f716-5730-11e5-8c53-9477e5f84ebd.png)

I have no idea why this is happening, and when I was on the version in the normal Ubuntu repositories, it didn't do this.

**Comment by gregsheremeta** [comment] 2015-09-10 02:03
AAC or MP3? (Are you a Pandora One sub?)

Some things to try:

Make a fresh test account. Does it do it on that new account?

Also, don't use Pandora for several hours and try again later. Does that help?

**Comment by MC42** [comment] 2015-09-10 02:17
Not a pandora one sub, I believe it's whatever the default is (pithos.ini says medium quality)

Your last item, I've tried that.  Days have passed, the issue still persists.  

Is there a way to open a configuration menu and check?  (I'm not familiar with the new version's menu, and haven't seen a config "gear".

**Comment by gregsheremeta** [comment] 2015-09-10 02:18
There is a 'preferences' option in the menu.

**Comment by MC42** [comment] 2015-09-10 02:22
![selection_005](https://cloud.githubusercontent.com/assets/6531081/9778644/44e31e62-5741-11e5-99d6-e06938de7b6c.png)

(pardon me for being a fool), where would that be?

**Comment by gregsheremeta** [comment] 2015-09-10 02:25
No problem. Just upgraded Ubuntu huh? Sorry about that :)

Looks at the hidden 'Pithos' menu in the top left of this screenshot.

https://camo.githubusercontent.com/574cce5f99d8f70bc72f79b8e6e1a807a8a86ef4/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323234383239332f323234323134312f61643230663765382d396366372d313165332d383230342d6266313037353832313465382e706e67

**Comment by MC42** [comment] 2015-09-10 02:31
Thanks, got it open.  I don't have a format option, in the config file, or in the menu.

I tried changing qualities (from medium to high), and the problem still persists.  
![selection_006](https://cloud.githubusercontent.com/assets/6531081/9778734/79882dc8-5742-11e5-9857-d01e9da9f28e.png)

**Comment by gregsheremeta** [comment] 2015-09-10 02:39
Ok. Try making a new account on pandora.com and fill in the new details there. Restart pithos. Still happens?

**Comment by MC42** [comment] 2015-09-10 02:44
I did so, and it still happens.   I'm just confused at this point...

**Comment by MC42** [comment] 2015-09-10 02:48
I appologize for the closing and re-opening, I was hasty.  The issue still persists...

**Comment by MC42** [comment] 2015-09-10 02:56
I've also tried building from 2 repositories, still results in the same issue.  (dev & main).

**Comment by TingPing** [comment] 2015-09-10 06:45
@gregsheremeta mp3 (aka high) is pandora one only.

**Comment by MC42** [comment] 2015-09-10 10:50
High plays, but suffers the same issue as the issue report is about.  Medium is what I was on until I was asked to test.

**Comment by gregsheremeta** [comment] 2015-09-11 01:33
Ok. So this is a known issue with AACs, but it usually goes away after a while afaik.

Looks like we have some more buffering improvements to do :)

**Comment by MC42** [comment] 2015-09-11 01:45
Allright, thank you for looking.  Sorry I can't contribute more, my coding knowledge is rather limited.

**Comment by gregsheremeta** [comment] 2015-09-11 01:50
Sure, sorry it's not working out!

**Comment by jkugler** [comment] 2015-09-17 17:35
Is this a duplicate of #224?

**Comment by MC42** [comment] 2015-09-17 20:18
@jkugler, only the first bit of behavior listed in #224 is similar.  The rest of the symptoms listed in #224 are not present for me.

**Closed** 2020-01-06 05:18 UTC
