### ISSUE TITLE
Mediakeys don't work in Version 1.5 even though they are working in 1.1.2

### ISSUE THREAD

**Issue by lpp7777** [pithos/pithos#613] opened 2020-04-09 23:06 UTC
Media keys don't work in Version 1.5 even though they are working in 1.1.2 on the same laptop the same OS (Kubuntu 19.10).

How to reproduce the problem:
Open Pithos Version 1.5
Open Preferences / Ctrl+P
Click Mediakeys      It does not slide to On unlike Version 1.1.2

Please could you help? Thanks!

**Comment by lpp7777** [comment] 2020-06-25 23:48
Details of the Laptop is Lenovo Ideapad 330S-15ARR: This laptop has dedicated Play/Pause, Stop, previous song, and next song buttons that are located over the Numbers key. When I say dedicated media keys I mean the Function button does not have to be pressed as may be required on some laptops.

**Comment by TingPing** [comment] 2020-06-26 00:31
Likely a duplicate of #595

**Closed by TingPing** 2020-06-26 00:31 UTC
