### ISSUE TITLE
Stuck in buffering loop, no sound

### ISSUE THREAD

**Issue by dkogias** [pithos/pithos#150] opened 2015-01-08 20:01 UTC
Pithos 1.0.1 from Fedora 21 repo.
Account works fine in web (HTML5) player; no Pandora One.
Pithos is stuck in this:
![screencast](https://cloud.githubusercontent.com/assets/428200/5669617/d45abea8-972d-11e4-8392-04b152a58eca.gif)

**Comment by dan9550** [comment] 2015-01-15 11:57
Having the same issue myself, i did just wait about 5+ minutes and its started playing but having to stop and buffer somewhat frequently. Running on Ubuntu 14.10, free Pandora account.

**Comment by TingPing** [comment] 2015-01-15 19:12
Duplicate of #113

**Closed by TingPing** 2015-01-15 19:12 UTC
