### ISSUE TITLE
1.2 crashes on my Lubuntu installs

### ISSUE THREAD

**Issue by Organic-Marble** [pithos/pithos#322] opened 2016-07-28 17:39 UTC
Installed on 32 bit Lubuntu from PPA, and 64 bit Lubuntu from .deb 

Both crash with following output when run from command line

```
Traceback (most recent call last):
File "/usr/bin/pithos", line 43, in <module>
from pithos import application
File "/usr/lib/python3.5/site-packages/pithos/application.py", line 26, in <module>
from .pithos import PithosWindow
File "/usr/lib/python3.5/site-packages/pithos/pithos.py", line 41, in <module>
from . import AboutPithosDialog, PreferencesPithosDialog, StationsDialog
File "/usr/lib/python3.5/site-packages/pithos/PreferencesPithosDialog.py", line 22, in <module>
from .util import get_account_password, set_account_password
File "/usr/lib/python3.5/site-packages/pithos/util.py", line 21, in <module>
gi.require_version('Secret', '1')
File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Secret not available
```

**Comment by TingPing** [comment] 2016-07-28 17:59
Duplicate of #321 and should already be fixed in pithos - 1.2.0-1ppa5

**Closed by TingPing** 2016-07-28 17:59 UTC
