### ISSUE TITLE
Seemingly invalid media URL

### ISSUE THREAD

**Issue by person666** [pithos/pithos#436] opened 2017-03-23 03:13 UTC
Today I started getting this error:
`ERROR - pithos:on_gst_error:961 - Gstreamer error: gst-resource-error-quark: Bad Request (5), gstsouphttpsrc.c(1375): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin4/GstSoupHTTPSrc:source:
Bad Request (400), URL: THE_URL, Redirect to: (NULL), 5`
THE_URL does not seem to exist on the server when I manually try to get it.
Could Pandora have changed something?
I have gsteamer update and working with other urls.

**Comment by JasonLG1979** [comment] 2017-03-23 03:32
Duplicate of https://github.com/pithos/pithos/issues/435

**Closed** 2017-03-23 22:28 UTC

**Comment by JasonLG1979** [comment] 2017-03-23 23:30
So @person666 I assume it was a Pandora issue and has cleared it self up?
