### ISSUE TITLE
Support for Compiz "Window Rules"

### ISSUE THREAD

**Issue by machineghost** [pithos/pithos#286] opened 2016-04-05 18:06 UTC
I use Pithos with several workspaces, and I like for Pithos to move with me to whichever workspace I happen to be on (ie. I want it to be "sticky" or "Always on Visible Workspace").  Other users might want Pithos to always maximize/re-size/prevent re-sizing/etc.

All of this is possible with Compiz's "Windows Rules" ... except those rules need to be defined by a window class/name/title.  Obviously title won't work (as it changes with the song), but `class=Pithos` or `name=Pithos` _should_ work.  For some reason however, they don't.

If there's any way to "fix" Pithos's class/name, so that the Compiz Windows Rules could be applied to it, it would be very handy.  Thanks.

**Comment by TingPing** [comment] 2016-04-05 18:10
> https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-wmclass
> Don’t use this function.

Looks like we can use `gtk_window_set_role()` though.

**Comment by TingPing** [comment] 2016-04-05 18:13
Want to test this:

```diff
From c2db4740e475f4563b9fed73d3756f98c0393d72 Mon Sep 17 00:00:00 2001
From: Patrick Griffis <tingping@tingping.se>
Date: Tue, 5 Apr 2016 14:12:25 -0400
Subject: [PATCH] Set window role

---
 data/ui/PithosWindow.ui | 1 +
 1 file changed, 1 insertion(+)

diff --git a/data/ui/PithosWindow.ui b/data/ui/PithosWindow.ui
index 3b9c8d9..e582c4a 100644
--- a/data/ui/PithosWindow.ui
+++ b/data/ui/PithosWindow.ui
@@ -10,6 +10,7 @@
   </object>
   <template class="PithosWindow" parent="GtkApplicationWindow">
     <property name="title" translatable="yes">Pithos</property>
+    <property name="role">Pithos</property>
     <property name="default_width">500</property>
     <property name="default_height">360</property>
     <property name="icon_name">pithos</property>
-- 
2.8.0
```

**Comment by machineghost** [comment] 2016-04-06 22:54
Thanks for the response!

I actually installed Pithos using a package manager, which means I don't have anywhere to call `git` from.  However, I did find a `/usr/share/pithos/ui/PithosWindow.ui` file and (with the power of `sudo`) was able to edit it and add that line of XML ...

... except there was a problem: my (v0.3.17) XML has an `<object>` instead of a `<template>`, and it lacks a `parent="GtkApplicationWindow"` attribute:

    <object class="PithosWindow" id="pithos_window">
    <property name="title" translatable="yes">Pithos</property>
    <property name="default_width">500</property>
    <property name="default_height">360</property>
    <property name="icon_name">pithos</property>
    <signal name="destroy" handler="on_destroy"/>
    <child>

I tried adding the `<property>` manually, and also tried adding the `parent` attribute and changing the `<object>` to a `<template>`.  That just got me errors like `Unhandled tag: 'template'`, but my window rule  still didn't work (even when I changed it to match on role).

So, while I'd be happy to help beta test, I'll either need a patch for the 0.3.17 XML, or I'll need to wait for the repository to  have the `<template>` version.

**Comment by TingPing** [comment] 2016-04-06 23:29
You only need to add that single line, everything around it can be ignored.

**Comment by hackel** [comment] 2016-04-07 18:06
I think you must have a different problem.  Specifying `class=Pithos` works fine for me.  I use it to size the window, but I just confirmed it works for sticky state as well.  You can also do partial-title matches, so `title=Pithos` works just fine as well.

**Comment by machineghost** [comment] 2016-04-07 18:48
Well adding (just) that line didn't help, and based on @hackel's comment it seems like I shouldn't really need it, so something must just be broken with my Compiz setup.  Instead of banging my head against the wall with it,  I'm going to try using DevilsPie instead.

Thanks all, and sorry for the false report.

**Comment by hackel** [comment] 2016-04-11 16:54
Nice, I wasn't aware of Devil's Pie.  It will be essential as Compiz is going away soon anyway.

**Comment by TingPing** [comment] 2016-07-02 18:55
I'll be closing this since nothing was ever confirmed to be a problem on Pithos' end.

**Closed by TingPing** 2016-07-02 18:55 UTC
