### ISSUE TITLE
feature request - ability to add a station by artist and/or song when right-clicking on a playlist entry

### ISSUE THREAD

**Issue by neoh4x0r** [pithos/pithos#385] opened 2017-01-01 08:13 UTC
Right now the only way to add a station would be to open the station manager, click the 'add station' + button and then search for an artist or song.

But I was hoping it wouldn't be, too, difficult to add this functionally to the playlist's context menu.

If a song is playing and you like the artist and/or song you could then right-click the entry and add
a new station based on either the artist or just the song (i'd like to see both options).

Thanks.

**Comment by JasonLG1979** [comment] 2017-01-01 08:33
I actually started work on that a few months ago. Never finished though.
https://github.com/pithos/pithos/pull/291

The reason being is how Pandora stations work. Basically stations start from seeds(artist, album or gene). Where you can have a station with multiple seeds you can not have 2 stations that contain the same seed. So you can have station 1 with seeds a, b, c and station 2 with seeds x, y, z you can't create a new station with seeds a, b, c, x, y, z. If you try it will silently fail. It won't throw any errors or anything it just won't work. You can get seed Id's from the stations and you can create stations based on either the song or artist with the trackToken but it's not clear how to compare seed Id's and trackTokens so that if you right click a song and you already have a station with that song or artist it will only show the appropriate menu options. Directly comparing song metadata to the seed description doesn't even work because it's inconsistent. I can create a station artist based station for "Some Random Artist" and the returning seed description string may or may not match "Some Random Artist".

**Comment by neoh4x0r** [comment] 2017-01-01 08:38
@JasonLG1979 I only say that because the official Pandora apps on my TV (as well as the web based app) can add a station based on both the artist and track.

I did this for an artist I was listening to in pithos through the webapp, and then synced the stations in pithos.
Basically by selecting 'Song info' from the context menu which launched my browser -- from there I could use Pandora's web interface to add artist as a station (and pithos's stations list was updated when I refreshed it).

Are you saying that this is not possible with Pandora or just with Pithos?

**Comment by JasonLG1979** [comment] 2017-01-01 08:42
We aren't an official client. We rely on the reverse engineering of others and our own tinkering to figure out the Pandora API. We don't have access to the real API docs like the the people who write official Pandora apps.

The best I can do at this point is always present the option to create a station based on the song and artist for every song and not check anything. Since it silently fails it doesn't hurt anything except a wasted network call. But then I'd get a bunch of bug reports about how people tried to add a station but it didn't show up.

**Comment by JasonLG1979** [comment] 2017-01-01 08:47
Don't get me wrong I think it's a great feature. There are a lot of feature that the official apps have that I'd love to add.

**Comment by neoh4x0r** [comment] 2017-01-01 08:49
@JasonLG1979 
When you use the station manager to search for a song or artist it seems to be failry accurate. 

What if the search api that pithos uses could be updated to make external calls into it?

The artist/song that I was adding was: Bjok/Army Of Me on Album Greatest Hits.

If I typed 'Bjok' into the search dialog for the station manager...the matching result is 'Bjok (artist)'
If I typed 'Army Of Me..the matching result is 'Army Of Me by Bjok'

Would it not be possible to automate the search and match based on that criteria?
I know it would not be 100% accurate.

Another option might be to present the user with a dialog to select from a list of matches.

**Comment by JasonLG1979** [comment] 2017-01-01 08:51
"fairly accurate" still = bug reports.

**Comment by JasonLG1979** [comment] 2017-01-01 08:54
> Another option might be to present the user with a dialog to select from a list of matches.

That would just be duplicating the station management dialog. When I get some free time I may revisit this and see if I can't find a way to do direct comparisons so it's accurate.

**Comment by neoh4x0r** [comment] 2017-01-01 09:02
@JasonLG1979 
It wouldn't have to duplicate the station management dialog if the search code was moved into function that could be called by other code, this function could also do filtering and return a list of matches.

if the search was initiated through the station management dialog -- it could return all matches without any filtering.

The filtering could use the following...Assuming that artist is Bjok and the song is Army Of Me.

For the artist: match all search result strings by "Bjok (artist)"
For the song: match all search result strings by "Army Of Me (by Bjok)"

**Comment by JasonLG1979** [comment] 2017-01-01 09:29
> It wouldn't have to duplicate the station management dialog if the search code was moved into function that could be called by other code, this function could also do filtering and return a list of matches.

I'm not talking about duplication as far as code. I'm talking about duplicating functionality.

> if the search was initiated through the station management dialog -- it could return all matches without any filtering.
> 
> The filtering could use the following...Assuming that artist is Bjok and the song is Army Of Me.
> 
> For the artist: match all search result strings by "Bjok (artist)"
> For the song: match all search result strings by "Army Of Me (by Bjok)"

Filtering is not problem. The problem aside from duplication of functionality is that your way you'll have to do API calls to Pandora possibly several. That makes for a laggy experience. Entering text into a search entry a user might expect a little lag. You don't expect lag from a context menu. What I'm talking about is having all the info I need by the time the stations and songs have been received. The only call I want to make is adding the new station.

**Comment by neoh4x0r** [comment] 2017-01-01 11:58
> The problem aside from duplication of functionality is that your way you'll have to do API calls to Pandora possibly several.
Doesn't the station management dialog do that?

> What I'm talking about is having all the info I need by the time the stations and songs have been received.
Doesn't pithos already have the needed information for a playing song?
That is the artist, song title, etc

**Comment by JasonLG1979** [comment] 2017-01-01 18:06
No what I want is a way to directly compare the station seeds to the selected song. You are missing the point. We already have all the info we need to create a station based on the song or artist of a selected song. We just currently lack the ability to tell with any certainty if that selected song or artist is already a seed.

**Comment by neoh4x0r** [comment] 2017-01-02 05:21
@JasonLG1979 
I see...the only issue is possibly having duplicated stations (and not that those stations couldn't be added).

Alright, thanks.

**Comment by JasonLG1979** [comment] 2017-01-02 06:10
> I see...the only issue is possibly having duplicated stations (and not that those stations couldn't be added).

No the issue is quite the opposite, as I said you can't create a station with an existing seed. As in if you have a station that contains "Super Awesome Song" as a seed if you try to create a new station with "Super Awesome Song" as a seed it will fail. When it does fail you may wonder why and file a bug report. I need to be certain that the user does not have the option create stations that will fail. I can not do that at the moment.

> PS: This information might be helpful (Retrieve extended station information station.getStation ) which includes:

I have read those docs a thousand times. I've even found a couple methods myself that are not documented there. (See the explicit content filter) if you look in:

 https://github.com/pithos/pithos/pull/291/commits/6ae9d123b00f6b725629548467be6c6b6857672e#diff-7e23d25b95a4c2d86799f64916097ba3

You'll see I use ```'includeStationSeeds': True``` to get the seed info. As I've said at this point the seed info that is returned doesn't seem to be directly comparable to the into returned with the songs, not even the song or artist names match up all the time.

**Comment by JasonLG1979** [comment] 2017-01-02 06:17
The best I could do is always give the user the option and if it fails show a little pop up that says something to the effect that a station based on the artist/song already exists so a new one could not be created.

**Comment by JasonLG1979** [comment] 2017-01-02 06:20
Not the best solution, but @TingPing what do you think? There really should be at least something like that for the station search window.

**Comment by JasonLG1979** [comment] 2017-01-02 06:29
@TingPing And I just noticed that when you do add a station in the search dialog it just adds the new station instead of refreshing all the stations as it should. So you end up with duplicate stations for that session if you add a station with existing seed. If you quit Pithos and start it again the duplicate goes away.

**Comment by JasonLG1979** [comment] 2017-01-02 06:29
I'll fix that as soon as I get a chance if you don't want to.

**Comment by neoh4x0r** [comment] 2017-01-02 06:42
@JasonLG1979 
So what you are saying is that when selecting a station from the search dialog you cannot compare that station's id to an id of an existing station?

**Comment by JasonLG1979** [comment] 2017-01-02 07:08
I can. I'm working on it. Basically if you try to create a station with an existing seed it just returns the existing station that contains that seed. My plan is to compare the returned station to the exsisting stations and if the id's already exists I can pop up a window that basically says "Station: Super Fresh Jams already has Super Awesome Song as a seed. You can't create a station based on Super Awesome Song but would you like to listen to  Station: Super Fresh Jams?" or something to that effect. The same dialog could be used for a context menu in the song tree.

**Comment by JasonLG1979** [comment] 2017-01-02 07:17
In the context menu you don't need to do a search. You can (attempt to) create a station directly with:

``station.createStation`` with the args ```trackToken``` and ```musicType``` where trackToken is the trackToken returned with the song and musicType is either 'song' or 'artist' depending on if you want a station based on the song or artist.

**Comment by JasonLG1979** [comment] 2017-01-02 07:34
> If it is a stationToken, could that not be compared to stationTokens from the list of known stations?

As far as I know that stationToken is unique to your Bjork station, and is not directly comparable to anything. To be able to make sense out of the stationToken(or any other Token/Id we get from Pandora for that matter) we'd have to know how they come up with them. Which we don't. So at the moment they are just magic Tokens/Ids.

**Comment by neoh4x0r** [comment] 2017-01-02 08:28
@JasonLG1979 

Both of these urls go to the same station:
https://www.pandora.com/station/3463069669211457771
https://www.pandora.com/station/3464122803818974278

I just tried another station I found on google: https://www.pandora.com/station/2190650977068628604
This is the url that was created: https://www.pandora.com/station/3464140262824429803

Your url: 3464122803818974278 
and this new url: 3464140262824429803

both have  34641 at the beginning -- so I'm guessing that the first 5 digits will be the same for any station created, played, or viewed on the same day (as for the other 14 numbers -- who knows).

**Comment by JasonLG1979** [comment] 2017-01-02 08:54
> Both of these urls go to the same station:
> https://www.pandora.com/station/3463069669211457771
> https://www.pandora.com/station/3464122803818974278
> 
> I just tried another station I found on google: https://www.pandora.com/station/2190650977068628604
> This is the url that was created: https://www.pandora.com/station/3464140262824429803
> 
> Your id: 3464122803818974278
> and the id I got for this new station: 3464140262824429803
> 
> both have 34641 at the beginning -- so I'm guessing that the first 5 digits will be the same for any station created, played, or viewed on the same day (as for the other 14 numbers -- who knows).

Who knows? The last digits maybe may represent you as a user? Like I said we don't know how the Id's are generated. I'll investigate further, but for now the 1st thing is fixing the station search, that's a bug. Bugs 1st, new features 2nd.

**Comment by JasonLG1979** [comment] 2017-01-13 23:52
@neoh4x0r I put in a PR for the bug. As soon as it's merged I'll work on adding the ability to add stations based on artist or song in the song tree context menu.

**Comment by neoh4x0r** [comment] 2017-01-14 00:03
@JasonLG1979 sounds good.

**Comment by neoh4x0r** [comment] 2017-02-11 12:28
@JasonLG1979  @TingPing 
I just tested commit 5f34953f00704b6609d700d51a8cf8416616e58b

The things is....I don't add any variety to my stations so every station is based on a single artist (of course other similar songs will played based on data from th genome project).

However this new update seems to work perfectly to detect that a station already exists and behaves more like the official Pandora app now.

Such as if I use the pandroa app on my Samsung tv and attempt to add an artist that already exists, it would auto-switch to the existing station -- pithos does it better though, by asking before it switches.

I guess this is the best thing for now (until we could do the same thing by right-clicking on the a song in the playlist -- as this issue mentions)

But anyway, 
This works perfectly, thanks....

**Comment by JasonLG1979** [comment] 2017-02-11 15:33
> Such as if I use the pandroa app on my Samsung tv and attempt to add an artist that already exists, it would auto-switch to the existing station -- pithos does it better though, by asking before it switches.

I thought it was better that way. Just switching stations with no explanation is potentially confusing.

> I guess this is the best thing for now (until we could do the same thing by right-clicking on the a song in the playlist -- as this issue mentions)

That functionality once it lands will work very much the same. Since thee's no way for us to know that a potential song or artist is an existing song seed ahead of time we would always present the option in the right click menu. If a duplicate station is returned we would show the same warning message.

**Comment by JasonLG1979** [comment] 2017-02-11 15:37
We are gearing up for a new release ATM and after that before anything else I have promised @TingPing that I'd split out the player from the main logic before I do anything else so it ma still be a bit before this feature is added but it's on my roadmap. It will make it in there eventually I'm pretty sure.

**Comment by JasonLG1979** [comment] 2017-04-16 21:08
@neoh4x0r as promised there you go, a PR in in.

**Comment by JasonLG1979** [comment] 2017-04-16 22:13
![screenshot from 2017-04-16 17-12-04](https://cloud.githubusercontent.com/assets/6667703/25074732/079bf02a-22c8-11e7-87a8-49471757c5d0.png)

**Comment by neoh4x0r** [comment] 2017-04-16 22:50
@JasonLG1979 that's awesome....
I guess the next step would be to merge the PR into master

**Comment by JasonLG1979** [comment] 2017-04-16 23:02
Yep. That's on the up to the Grand Master Gatekeeper, @TingPing lol!!! It'll get there.

**Comment by JasonLG1979** [comment] 2017-04-16 23:08
It works very similar to adding a station via the stations dialog in the way that if the station already exists you get the same warning dialog with the option to listen to the existing station if you aren't already. I opted to not show the song title or artist name in the right click menu because things get a little weird with film scores and such. And it's kinda redundant anyway.

**Closed** 2017-04-20 23:47 UTC
