### ISSUE TITLE
Stuck at "Buffering..." during playback

### ISSUE THREAD

**Issue by levibostian** [pithos/pithos#416] opened 2017-02-02 21:21 UTC
I am having an issue with Pithos where the music playback will stop and display "Buffering..." until I do one of the following:
* Quit Pithos and go back in. 
* Change the station and change it again to the station I had it on previously.
* Double click on the song below it if there is one.

When I do one of the following commands above (except for quit and coming back in) the bottom left of the screen reads "Logging in." and then "Getting songs." and then it begins to play as normal. 

While I play, after an hour or few hours, at random the song will go into Buffering state. I need to do one of the following to refresh Pithos and begin playing again. 

---

I am running Pithos from master branch build from source. Build f00934f. Raspberry Pi 2. Raspbian. Lowest quality music playback (thought it would make it better?) 

I was having other buffering issues before, but after updating to the latest version this is my newest issue.

**Comment by JasonLG1979** [comment] 2017-02-02 21:22
https://github.com/pithos/pithos/pull/402 fixes this. Just needs to be merged.

**Comment by JasonLG1979** [comment] 2017-02-13 01:11
Closing this as a Duplicate of https://github.com/pithos/pithos/issues/342 (another bug you reported) Gstreamer on ARM must just be buggy.

**Closed by JasonLG1979** 2017-02-13 01:11 UTC
