### ISSUE TITLE
"Stations" menu item does not work

### ISSUE THREAD

**Issue by assmblyreq** [pithos/pithos#624] opened 2020-07-25 15:44 UTC
As stated in title, selecting "Stations" in the Pithos menu doesn't work.

I am using the 1.5.0 client in Debian 10.4

Start client as "pithos --debug --verbose" gives the following when selecting "Stations" button:

DEBUG - pithos:react_to_buffering_mesage:1160 - Buffer overrun
DEBUG - pithos:react_to_buffering_mesage:1163 - Song starting
Traceback (most recent call last):
  File "/usr/local/share/pithos/pithos/application.py", line 193, in stations_cb
    self.window.show_stations()
  File "/usr/local/share/pithos/pithos/pithos.py", line 1449, in show_stations
    self.stations_dlg = StationsDialog.StationsDialog(self, transient_for=self)
  File "/usr/local/share/pithos/pithos/StationsDialog.py", line 55, in __init__
    self.modelsortable = Gtk.TreeModelSort.new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'new_with_model'

**Comment by TingPing** [comment] 2020-07-25 16:11
Duplicate of #615

**Closed by TingPing** 2020-07-25 16:11 UTC

**Comment by assmblyreq** [comment] 2020-07-25 16:22
Fixed.  Thank you!
