### ISSUE TITLE
The Mediakeys plugin causes Pithos to segfault under GNOME+Wayland on Ubuntu 17.04

### ISSUE THREAD

**Issue by BHSPitMonkey** [pithos/pithos#448] opened 2017-04-17 19:23 UTC
Everything works fine if I log into a Unity or GNOME+X session, but when I log in with GNOME+Wayland I get an immediate segmentation fault when I try to start Pithos.

---

**Update:** For anyone here looking for a solution without wanting to read the full context below, here's how to get it working until an official patch is out:

1. Log in to an X (non-Wayland) session
2. Launch Pithos
3. Open Pithos's settings
4. Turn off the **Mediakeys** plugin
5. You can switch back to Wayland now; Pithos should work

**Comment by JasonLG1979** [comment] 2017-04-17 19:53
Wayland support in Ubuntu is not the greatest. I have no problems in Fedora 25 with Wayland and Pithos.

**Comment by BHSPitMonkey** [comment] 2017-04-17 20:01
Yeah, these problems are definitely understandable at this stage of Wayland's adoption. Pithos is one of two applications I use regularly that won't start in this session so it stands out to me more, but using pianobar instead or switching back to X are both tenable workarounds for me at the moment. Just giving us somewhere to track this for now since I haven't see a similar report yet.

**Comment by JasonLG1979** [comment] 2017-04-17 20:08
> Just giving us somewhere to track this for now since I haven't see a similar report yet.

That's fine. I expect Wayland support to hopefully improve in Ubuntu with the killing or Mir on the desktop. Hopefully Canonical actually puts some work into fixing it on Ubuntu? Time will tell I guess how much they plan on giving back to the desktop?

**Comment by JasonLG1979** [comment] 2017-04-17 20:09
Do you get any kind of traceback?

**Comment by JasonLG1979** [comment] 2017-04-17 20:10
I have a Ubuntu 17.04 GNOME VM I'll see what I get.

**Comment by JasonLG1979** [comment] 2017-04-17 20:17
It's the Mediakeys plugin. If you disable it in X session Pithos runs fine in the Wayland session. @TingPing?

**Comment by TingPing** [comment] 2017-04-17 22:15
Yell at your distro to upgrade keybinder3 to 0.3.2 as it fixes crashing on Wayland. Normally Pithos wouldn't even attempt to use keybinder on Gnome but they broke their dbus service in 3.24: https://bugzilla.gnome.org/show_bug.cgi?id=781326

**Comment by JasonLG1979** [comment] 2017-04-17 23:34
Well good job outa them. I thought things were suppose to relatively stable in GNOME 3.30+? Is there just no DBus mediakey interface in GNOME 3.24? Seems like a pretty big regression...

**Comment by TingPing** [comment] 2017-04-17 23:50
`gnome-settings-daemon` split all of its plugins into different processes, probably to better handle crashes and maybe even potential sandboxing. They just didn't realize people relied on the bus name...

**Comment by JasonLG1979** [comment] 2017-04-18 02:57
> They just didn't realize people relied on the bus name...

Because who'd a though that right. That people would have depended on interfaces that were specifically designed for interacting with the services/plugins. Brilliant...

**Comment by JasonLG1979** [comment] 2017-04-18 03:05
Can we not just try to bind to the new interface? I also noticed that the Mediakeys plugin doesn't have a on_prepare function to allow for graceful failure.

**Comment by TingPing** [comment] 2017-04-18 03:13
> Because who'd a though that right. That people would have depended on interfaces that were specifically designed for interacting with the services/plugins. Brilliant...

The problem is the documentation pointed to a different bus name `org.gnome.SettingsDaemon.MediaKeys` and the real implementation only exposed `org.gnome.SettingsDaemon`. So its a long standing bug really that everybody relied upon.

> Can we not just try to bind to the new interface? 

It doesn't own any bus name atm.

**Comment by JasonLG1979** [comment] 2017-04-18 03:16
In the mean time I guess we need to check the keybinder3 version if the user is running in a wayland session then?

**Comment by JasonLG1979** [comment] 2017-04-18 03:19
> It doesn't own any bus name atm.

So it's completely useless. Great. Double good job out a them. Break an existing working interface by basically just taking it away...

**Comment by JasonLG1979** [comment] 2017-04-18 04:06
@TingPing I can't even get it fail gracefully. Even inside a try except block keybinder.bind causes a segfault... And I can't get a version from keybinder. Do you know of a way to check the actual version of keybinder?

**Comment by JasonLG1979** [comment] 2017-04-18 04:08
At this point i'm wondering if we shouldn't just disable keybinder on Ubuntu 17.04 in wayland?

**Comment by JasonLG1979** [comment] 2017-04-18 04:12
```python
import platform
print(platform.linux_distribution())
```

Gets me:
```
('Fedora', '25', 'Twenty Five')
```

In Fedora 25.

**Comment by JasonLG1979** [comment] 2017-04-18 04:26
```python
    def bind_keybinder(self):
        display = self.window.props.screen.get_display()
        on_x = type(display).__name__.endswith('X11Display')
        if 'Ubuntu' in platform.linux_distribution() and not on_x:
            return False
        ....
```

Should stop us from touching keybinder in Ubuntu on in a wayland session. @TingPing?

**Comment by TingPing** [comment] 2017-04-18 04:28
@JasonLG1979 We don't need to care what version it is. If wayland just never even attempt keybinder at all, it will never work.

**Comment by JasonLG1979** [comment] 2017-04-18 04:30
> We don't need to care what version it is. If wayland just never even attempt keybinder at all, it will never work.

You said it was fixed in keybinder 0.3.2 if we can check that version we can tell if it's going to crash.

**Comment by TingPing** [comment] 2017-04-18 04:30
Yes new keybinder internally does `if wayland: return` to be safe but we can do that outselves.

**Comment by JasonLG1979** [comment] 2017-04-18 04:34
Right on just disable keybinder in wayland all together for now then?

**Comment by JasonLG1979** [comment] 2017-04-18 04:36
We still need to have a prepare method so the plugin is at least greyed out.

**Comment by TingPing** [comment] 2017-04-18 04:38
Yup. Oh also this would be the way to check the version: https://github.com/kupferlauncher/keybinder/commit/6efbdeb9d5e8a5ecee6e06a9ea1162d7cf7b304b

**Comment by JasonLG1979** [comment] 2017-04-18 05:13
We should just check our self. To use that we'd need to use hasattr and check our self anyway if that method doesn't exist.

**Comment by JasonLG1979** [comment] 2017-04-18 06:16
That plugin is a ClusterF#ck. i'm going to have to rewrite it...

**Comment by JasonLG1979** [comment] 2017-04-18 06:24
It would be nice if they had at least 1 property you could check for instead of having to grab the media keys...

**Comment by JasonLG1979** [comment] 2017-04-18 20:19
@BHSPitMonkey and @TingPing, there try that branch out. It should do the trick.

**Comment by JasonLG1979** [comment] 2017-04-18 23:53
Well @TingPing I think I figured out why that bus is unowned. In GNOME 3.24 it seems we get mediakeys for free. With that plugin rewrite of mine basically if you're on GNOME 3.24 and Wayland nothing should be loaded. And yet Pithos still responds to media key presses. I can even completely remove the plugin from the install and again Pithos will respond to mediakey presses.

**Comment by JasonLG1979** [comment] 2017-04-19 00:03
On GNOME 3.22 in Fedora 25 with the same setup mediakeys wise, I can enable and disable the plugin and Pithos will or won't respond to the mediakeys accordingly.

**Comment by JasonLG1979** [comment] 2017-04-19 00:08
It's going though MPRIS!!!

**Comment by TingPing** [comment] 2017-04-19 00:09
Yea, but it doesn't work as well as normal support, it won't regrab on focus so its basically useless for me.

**Comment by JasonLG1979** [comment] 2017-04-19 00:10
I'll test it out see what it does.

**Comment by JasonLG1979** [comment] 2017-04-19 00:18
> Yea, but it doesn't work as well as normal support, it won't regrab on focus so its basically useless for me.

Yep, it basically just grabs the 1st available player and the mediakeys control it. No focus regrab.

**Comment by JasonLG1979** [comment] 2017-04-19 00:19
It's better than nothing though.

**Comment by JasonLG1979** [comment] 2017-04-19 00:38
Keybinder sucks too. In my testing it fails with:
```** (pithos:3333): WARNING **: Binding 'XF86AudioPlay' failed!```

More often then not if there's already a player open. (quodlibet) I'm not sure if quodlibet is also falling back to Keybinder and that's why that happens. All in all though this is a rather inconsistent mess...

**Comment by JasonLG1979** [comment] 2017-04-19 01:19
I started a new issue to reference the fact that in GNOME 3.24 you can't disable mediakeys without disabling mpris. As there isn't(or at least shouldn't be) obvious connection between the 2.

**Comment by JasonLG1979** [comment] 2017-04-19 01:28
In the mean time @TingPing my PR at least stops the mediakeys plugin from crashing Pithos.

**Closed** 2017-04-20 20:20 UTC
Labels: upstream
