### ISSUE TITLE
Pause key isn't working

### ISSUE THREAD

**Issue by Pinguinguy** [pithos/pithos#476] opened 2017-05-30 18:25 UTC
When im listening to pithos  it would be nice to press the pause button on my keyboard and it paused in pithos. Im running Razer blackwidow chroma but if there is an universal way so it would work on all or many keyboards would be awesome.
Thx for your time

**Comment by JasonLG1979** [comment] 2017-05-30 18:28
That's between you the keyboard and your desktop environment. Pithos has a built in Media Keys plugin. You'll have to configure your media keys for that keyboard in you desktop environment.

**Comment by TingPing** [comment] 2017-05-30 18:50
To slightly expand that, enable the `mediakeys` plugin in preferences and it uses keybinder3 (which you may not have installed) to bind the `XF86AudioPlay` key on X11. So if it doesn't work hopefully that can help you track down where the issue is.

**Comment by JasonLG1979** [comment] 2017-05-30 18:53
Looking at that keyboard on Amazon it doesn't have dedicated media keys it's just got media controls printed on f1, 2, 3, 5, 6, 7 keys. Be aware that f1 is reserved for help in GNOME apps but other than that just have to whatever media keys you want to whatever f* keys you want. Pretty much all desktop environments have a way to map the media keys. Look for something like keyboard or keyboard shortcuts in your DE's settings.

**Comment by TingPing** [comment] 2017-05-30 19:12
Usually they have a function key, so its not literally `f1`.

**Comment by Pinguinguy** [comment] 2017-05-30 19:23
It dosen't work for me the keyboard bindings is right and the only application it don't work in is pithos but i will probably find something out soon. Just thought it wasn't an option as it didn't work for me and therfore write it here so that you could implement it but you already have sorry for wasting your time just because im stupid :P

**Comment by TingPing** [comment] 2017-05-30 19:25
As I said, you probably are just missing that package.

**Comment by JasonLG1979** [comment] 2017-05-30 19:49
> Usually they have a function key, so its not literally f1.

I have a similar type keyboard, as in no no dedicated media keys. The literal f1 key opens help on *most*gtk apps.

**Comment by JasonLG1979** [comment] 2017-05-30 19:51
@Pinguinguy what distro and what DE?

**Comment by Pinguinguy** [comment] 2017-05-30 20:10
Linux mint mate but didn't work on manjaro either

**Comment by TingPing** [comment] 2017-05-30 20:16
Mint and Manjaro both don't install optional dependencies by default.

**Comment by JasonLG1979** [comment] 2017-05-30 20:34
> Mint and Manjaro both don't install optional dependencies by default.

Mate shouldn't need Keybinder. It's *suppose* to bind keys with DBus. I'll do some testing.

**Comment by TingPing** [comment] 2017-05-30 20:46
Oh right. `pithos -v` would be helpful.

**Comment by JasonLG1979** [comment] 2017-05-30 21:01
@TingPing On Ubuntu Mate at least printing the app, action in mediakey_signal of the media keys plugin. app is showing up as "MsdMpris"...

**Comment by JasonLG1979** [comment] 2017-05-30 22:14
@TingPing Mate doesn't send focus events unless you minimize or maximize the window even then it doesn't set the GDK flags. So the keys are never grabbed. Connecting to 'notify::is-active' and doing:

```python
    def update_active(self, *ignore):
        if self.window.is_active():
            self.grab_media_keys()
```

Seems to work as expected in Mate anyway. I'll test it in GNOME.

**Comment by JasonLG1979** [comment] 2017-05-30 22:57
@Pinguinguy this branch should fix the issue. Can you give it a test?

**Comment by JasonLG1979** [comment] 2017-05-31 21:17
@TingPing connecting to 'notify::is-active' also seems to work as expected in GNOME in both X and Wayland.

**Comment by edgreenberg** [comment] 2017-06-20 15:58
I had this pithos on Fedora Mate 24 and the keyboard media keys worked fine:
```
pithos.noarch                    1.1.2-1.fc24                     rpmfusion-free
```

When I get the latest Pithos here (1.3.1) the media keys stopped working.  

I have the MediaKeys plugin installed.  I have all the plugins that came with the bundle enabled, except for the LastFM (scrobble) plugin. (I'm not sure about scrobbling, but I suspect I'd have to wash my hands afterwards.)

My notification icon is properly showing in the Fedora Mate system tray.  My notifications (nice yellow balloons) are showing on song changes, so the other plugins are OK, but Pithos 1.3.1 ignores my back, pause and forward keys.  

Exaile, the default media player, obeys these media keys. Also, my volume and mute keys are working. 

Hope this helps find the problem.  Anybody who can tell me what to do will be appreciated.

**Comment by JasonLG1979** [comment] 2017-06-21 14:48
@edgreenberg we know the cause of the issue. see: https://github.com/pithos/pithos/pull/477

**Comment by edgreenberg** [comment] 2017-07-05 15:56
I pulled the repo https://github.com/JasonLG1979/pithos/tree/connect-to-is-active-mediakeys-plugin and ran it on Fedora Core 24.  Still no response to the pause and skip forward key.  I disabled and re-enabled the media-keys plugin, and got entries in the console when I did. 
```
INFO - plugin:disable:65 - Disabling module mediakeys
INFO - mediakeys:on_disable:153 - Disabled dbus mediakey bindings
INFO - plugin:_enable:59 - Enabling module mediakeys
INFO - mediakeys:on_enable:135 - Bound media keys with DBUS 
```

Here's my full session:

```
edg@edglaptop jasonpithos(master) $ make run
  GEN      data/gschemas.compiled
env GSETTINGS_SCHEMA_DIR=./data ./bin/pithos -v
INFO - application:do_activate:172 - Pithos 1.3.1
INFO - pithos:init_core:330 - Created temporary directory /home/edg/.cache/pithos-hgww_aoa
INFO - plugin:on_got_bus:132 - Got session bus
INFO - plugin:enable:53 - Preparing module journald_logging
INFO - plugin:_enable:59 - Enabling module journald_logging
INFO - journald_logging:_on_logging_changed:56 - setting journald logging level to: verbose
INFO - plugin:enable:53 - Preparing module mediakeys
INFO - plugin:enable:53 - Preparing module notification_icon
INFO - notification_icon:on_prepare:99 - Checking if org.kde.StatusNotifierWatcher is owned
INFO - plugin:enable:53 - Preparing module mpris
INFO - plugin:_enable:59 - Enabling module mpris
INFO - plugin:enable:53 - Preparing module notify
INFO - plugin:enable:53 - Preparing module screensaver_pause
INFO - plugin:_enable:59 - Enabling module screensaver_pause
INFO - notification_icon:on_has_name_owner:66 - org.kde.StatusNotifierWatcher is owned: False
INFO - plugin:_enable:59 - Enabling module notification_icon
INFO - mpris:on_name_acquired:111 - Got bus name: org.mpris.MediaPlayer2.pithos
INFO - plugin:_enable:59 - Enabling module mediakeys
INFO - mediakeys:on_enable:135 - Bound media keys with DBUS org.mate.SettingsDaemon.MediaKeys
INFO - plugin:_enable:59 - Enabling module notify

(pithos:31119): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
INFO - pandora:connect:291 - Time offset is 1.5418848991394043
INFO - pithos:pandora_ready:594 - Pandora connected
INFO - pithos:process_stations:656 - Restoring saved station: id = 111646639781076953
INFO - pithos:station_changed:917 - Selecting station 111646639781076953; total = 7
INFO - pandora:get_playlist:396 - pandora: Get Playlist
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pithos:start_song:699 - Starting song: index = 0
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pithos:art_callback:839 - Downloaded album art for 0
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pithos:art_callback:839 - Downloaded album art for 1
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pithos:art_callback:839 - Downloaded album art for 2
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pithos:art_callback:839 - Downloaded album art for 3
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pithos:check_if_song_is_ad:1050 - Not an Ad..
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pandora:explicit_content_filter_state:308 - Explicit Content Filter state: False
INFO - pandora:explicit_content_filter_state:309 - PIN protected: False
INFO - plugin:disable:65 - Disabling module mediakeys
INFO - mediakeys:on_disable:153 - Disabled dbus mediakey bindings
INFO - plugin:_enable:59 - Enabling module mediakeys
INFO - mediakeys:on_enable:135 - Bound media keys with DBUS org.mate.SettingsDaemon.MediaKeys
INFO - pithos:on_gst_eos:1008 - EOS
INFO - pithos:start_song:699 - Starting song: index = 1
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
INFO - pithos:check_if_song_is_ad:1050 - Not an Ad..
INFO - pandora:audioUrl:509 - Using audio quality highQuality: 192 mp3
^CMakefile:1319: recipe for target 'run' failed
make: *** [run] Interrupt

edg@edglaptop jasonpithos(master) $

```

**Comment by JasonLG1979** [comment] 2017-07-05 20:19
@edgreenberg What version of Mate? They recently move to GTK3. I tested on Ubuntu Mate 17.04 with the latest stable Mate version at that time and it seemed to work rather well. I'll see what Exaile is doing maybe we can learn from them?

**Comment by edgreenberg** [comment] 2017-07-06 17:43
Jason.

MATE Desktop Environment 1.16.2

Running on Fedora Core 24.

**Comment by mtb-xt** [comment] 2017-11-22 03:34
Hi everyone, I've tried the patch in Cinnamon desktop on Archlinux, and the mediakeys do not work either.

**Comment by JasonLG1979** [comment] 2017-11-22 07:47
There are a couple mediakeys bugs currently, this one and on Fedora 27 they don't even bind even though the DBus addresses match up. I'll fire up a VM this weekend and test on all of the Gtk bases DE's and see if I can't figure this out.

**Comment by JasonLG1979** [comment] 2017-11-22 19:21
@mtb-xt and @TingPing I found the problem there was a typo in the mediakeys service name...

Here's a PR with a fix. https://github.com/pithos/pithos/pull/546

**Comment by mtb-xt** [comment] 2017-11-22 23:37
@JasonLG1979 thanks for the patch, I've tried it, and got some very weird results.

At first, nothing changed - the keys didn't work at all. But, I tried running clementine, so with clementine running, Cinnamon detected a media player running, and the media keys started working in pithos (yes, with clementine running) - they also only work, if I have cinnamons media player widget open... 

Sorry for a cellphone picture, couldn't figure out how to make a screenshot of an applet!
https://www.dropbox.com/s/1590e2h7zhtcs33/20171123_123241.jpg?dl=0 

so, the media keys are only working while this is active and a player recognized by cinnamon is running >_>

**Comment by JasonLG1979** [comment] 2017-11-23 05:27
The current trend is for Distros to use MPRIS as a hack for mediakeys bindings. I'm going to fire up a few distros in VM and try to get this squared away this weekend.

**Comment by JasonLG1979** [comment] 2017-11-23 05:27
I meant DE use mpris as a hack not distros...

**Comment by TingPing** [comment] 2017-11-23 06:14
I'm not sure its even a "hack", it can work fine the only difficulty is window focus for multiple players.

**Comment by JasonLG1979** [comment] 2017-11-23 07:48
That's what makes it totally not work... Just because it can work means you should do it. IMHO using MPRIS for mediakeys is an abuse of MPRIS. MPRIS is meant to be directly controlled by the user not by mediakeys. If you want to bind your mediakeys to MPRIS fine but it should not be the default behavior. It's just being lazy...

**Comment by JasonLG1979** [comment] 2017-11-23 07:48
*doesn't mean you should use it.

**Comment by JasonLG1979** [comment] 2017-11-23 13:12
@TingPing there's no way to tell which is the current active player definitively with MPRIS. In my extension  we cheat a little bit to decide which icon/song info to show in the panel. Basically sort the players by PlaybackStatus. Even that's not perfect.

**Comment by TingPing** [comment] 2017-11-23 15:49
@JasonLG1979 Yea absolutely, it would require a new extension where a signal was sent on focus or perhaps it keeps a focus timestamp as a property.

**Comment by JasonLG1979** [comment] 2017-11-23 16:16
So far in my testing of the Xfce, LXDE, MATE and Cinnamon Fedora 27 spins with git master:

Xfce and LXDE do not support DBus mediakeys.

Mate still doesn't update it focus correctly.

Cinnamon seems to work as expected. It grabs the keys on focus and sends key press signals. Other than that we have no control how it abuses MPRIS to fake mediakeys.

@TingPing I would like to work around the Mate bug by connecting to 'notify::is-active' if we are running in Mate.

**Comment by JasonLG1979** [comment] 2017-11-23 16:21
Oh, as a side note because of the way mediakeys work, basically apps steal them from each other, there is no way for us to control how or if the DE gives them back to Pithos if for example an app that has the keys is closed. The logical thing for a DE to do is try to give the keys back to the last app that grabbed them but that's not guaranteed to happen. So you may need to re-focus Pithos for it to re-grab the mediakeys.

**Comment by JasonLG1979** [comment] 2017-11-23 16:27
And 1 more thing. Pause doesn't work because we don't listen for Pause we listen for Play/Pause. That can easily be fixed also.

**Comment by JasonLG1979** [comment] 2017-11-23 17:12
@TingPing this should do the trick https://github.com/pithos/pithos/pull/547 merge this if you will and release the bug fix version.

**Comment by JasonLG1979** [comment] 2017-11-26 19:29
I'm going to close this as as far I can tell from my testing with GNOME, MATE and Cinnamon DBus mediakeys seem to work as expected. If anyone has any other issues just let me know.

**Closed by JasonLG1979** 2017-11-26 19:29 UTC
Labels: question

**Comment by TingPing** [comment] 2017-12-07 20:51
@JasonLG1979 I'm sure you'll love this: https://smdavis.us/2017/11/27/development-release-xfce-pulseaudio-plugin-0-3-3/

**Comment by JasonLG1979** [comment] 2017-12-07 21:00
At least the mpris mediakeys are optional. I'm working on something similar for Mate(a mpris panel widget) sans crappie mediakeys hack ofc...

**Comment by mknapik1** [comment] 2020-01-07 18:28
Found this recently and discovered another possiblity. Chrome recently started capturing the media keys and not letting Pithos handle them. I turned off Chrome's ability to capture Media Keys and that solved my problem.

**Comment by JasonLG1979** [comment] 2020-01-07 18:50
I think it depends on your DE.

In GNOME at least media keys use MPRIS by default. Newer Chrome version throw up a MPRIS interface. The problem is that the media keys are given to the latest app that throws up a MPRIS interface and the grabs and releases of apps that actually use the proper media keys interface are ignored. The result is that if you open Chrome after Pithos GNOME will always send media key events to Chrome regardless if it's actually playing anything creating a black hole basically.

There is talk of adding some kind of focus property to MPRIS to basically restore the previous grabs and releases of the media keys interface to make players play nice again.

Currently though it's basically broken.
